<template>
  <section class="tenants-page" aria-labelledby="tenants-title">
    <header class="page-heading"><div><span class="eyebrow">REGISTERED WORKSPACES</span><h2 id="tenants-title">租户管理</h2><p>只展示已完成注册的租户；备注仅供平台内部识别和运营跟进。</p></div></header>
    <section class="tenant-panel" aria-label="租户筛选和列表">
      <form class="filters" @submit.prevent="applyFilters"><el-input v-model="filters.keyword" clearable placeholder="按租户代码或名称搜索" aria-label="搜索租户" @clear="applyFilters" /><el-select v-model="filters.status" clearable placeholder="全部状态" aria-label="按状态筛选"><el-option label="正常" :value="1" /><el-option label="已停用" :value="0" /></el-select><el-button native-type="submit">筛选</el-button><el-button text @click="resetFilters">重置</el-button></form>
      <p v-if="error" class="error-message" role="alert">{{ error }}</p>
      <div class="table-wrap" :aria-busy="loading"><table class="tenant-table"><thead><tr><th>租户</th><th>租户代码</th><th>平台备注</th><th>状态</th><th>创建时间</th><th class="actions-col">操作</th></tr></thead><tbody><tr v-for="tenant in tenants" :key="tenant.id"><td class="tenant-name">{{ tenant.name }}</td><td><code>{{ tenant.code }}</code></td><td class="remark-cell"><span>{{ tenant.remark || '—' }}</span></td><td><el-tag :type="tenant.status === 1 ? 'success' : 'info'" effect="plain">{{ statusLabel(tenant.status) }}</el-tag></td><td>{{ formatTime(tenant.createTime) }}</td><td class="actions-col"><el-button text @click="openRemark(tenant)">编辑备注</el-button><el-button v-if="tenant.status === 1" text type="danger" @click="disableTenant(tenant)">停用</el-button><span v-else class="muted">不可用</span></td></tr><tr v-if="!loading && tenants.length === 0"><td colspan="6" class="empty-state">还没有已注册的租户</td></tr></tbody></table></div>
      <footer class="table-footer"><span>共 {{ total }} 个已注册租户</span><el-pagination v-model:current-page="page" v-model:page-size="pageSize" layout="prev, pager, next" :total="total" :page-sizes="[10, 20, 50]" @current-change="loadTenants" @size-change="changePageSize" /></footer>
    </section>
    <el-dialog v-model="remarkDialogVisible" title="编辑平台备注" width="480px" :close-on-click-modal="false"><p class="dialog-context">{{ selectedTenant?.name }} · 此信息仅在平台管理端可见。</p><el-form label-position="top" @submit.prevent="saveRemark(selectedTenant)"><el-form-item label="内部备注"><el-input v-model.trim="remarkForm.remark" type="textarea" :rows="4" maxlength="512" show-word-limit placeholder="例如：合同续约时间、运营跟进事项" /></el-form-item></el-form><template #footer><el-button @click="remarkDialogVisible = false">取消</el-button><el-button type="primary" :loading="savingRemark" @click="saveRemark(selectedTenant)">保存备注</el-button></template></el-dialog>
  </section>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { http } from '../../api/http'
const tenants = ref([]), total = ref(0), page = ref(1), pageSize = ref(20), loading = ref(false), error = ref('')
const remarkDialogVisible = ref(false), savingRemark = ref(false), selectedTenant = ref(null)
const filters = reactive({ keyword: '', status: undefined }), remarkForm = reactive({ remark: '' })
function requestParams() { return { page: page.value, pageSize: pageSize.value, keyword: filters.keyword || undefined, status: filters.status } }
async function loadTenants() { loading.value = true; error.value = ''; try { const response = await http.get('/platform/tenants', { params: requestParams() }); const data = response.data?.data || {}; tenants.value = data.items || []; total.value = data.total || 0; page.value = data.page || page.value; pageSize.value = data.pageSize || pageSize.value } catch (cause) { error.value = cause.response?.data?.msg || '租户列表暂时无法加载' } finally { loading.value = false } }
async function applyFilters() { page.value = 1; await loadTenants() }
async function resetFilters() { filters.keyword = ''; filters.status = undefined; await applyFilters() }
async function changePageSize(size) { pageSize.value = size; page.value = 1; await loadTenants() }
function openRemark(tenant) { selectedTenant.value = tenant; remarkForm.remark = tenant.remark || ''; remarkDialogVisible.value = true }
async function saveRemark(tenant) { if (!tenant) return; savingRemark.value = true; try { await http.patch(`/platform/tenants/${tenant.id}/remark`, { remark: remarkForm.remark || null }); tenant.remark = remarkForm.remark || null; remarkDialogVisible.value = false; ElMessage.success('平台备注已保存') } catch (cause) { ElMessage.error(cause.response?.data?.msg || '保存备注失败') } finally { savingRemark.value = false } }
async function disableTenant(tenant) { try { await ElMessageBox.confirm(`停用“${tenant.name}”后，该租户将无法登录。`, '确认停用租户', { confirmButtonText: '确认停用', cancelButtonText: '取消', type: 'warning' }) } catch { return } try { await http.post(`/platform/tenants/${tenant.id}/disable`); ElMessage.success('租户已停用'); await loadTenants() } catch (cause) { ElMessage.error(cause.response?.data?.msg || '停用租户失败') } }
function statusLabel(status) { return status === 1 ? '正常' : '已停用' }
function formatTime(value) { return value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '—' }
onMounted(loadTenants)
</script>

<style scoped>
.page-heading { display: flex; justify-content: space-between; align-items: flex-end; gap: 18px; margin-bottom: 25px; }.eyebrow { color: #526aaf; font-size: 11px; font-weight: 800; letter-spacing: .12em; }h2 { margin: 5px 0; color: #182541; font-size: 28px; letter-spacing: -.02em; }.page-heading p { margin: 0; color: #75819a; }.tenant-panel { overflow: hidden; border: 1px solid #e0e5f0; border-radius: 12px; background: #fff; box-shadow: 0 8px 28px rgba(42, 58, 103, .06); }.filters { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; padding: 18px 20px; border-bottom: 1px solid #e8ebf2; background: #fbfcff; }.filters :deep(.el-input) { width: 260px; }.filters :deep(.el-select) { width: 130px; }.table-wrap { overflow-x: auto; }.tenant-table { width: 100%; min-width: 920px; border-collapse: collapse; font-size: 14px; }.tenant-table th { padding: 12px 20px; background: #f6f8fc; color: #6e7991; font-size: 12px; font-weight: 700; letter-spacing: .04em; text-align: left; }.tenant-table td { padding: 15px 20px; border-top: 1px solid #edf0f5; color: #40506f; }.tenant-table tr:hover td { background: #fafbff; }.tenant-name { color: #1d2b49 !important; font-weight: 700; }.tenant-table code { color: #425a98; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }.remark-cell { max-width: 260px; }.remark-cell span { display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: #64708a; }.actions-col { text-align: right !important; white-space: nowrap; }.empty-state { padding: 38px !important; color: #8791a6 !important; text-align: center; }.muted { color: #98a1b2; }.table-footer { display: flex; justify-content: space-between; align-items: center; gap: 16px; padding: 14px 20px; color: #778298; font-size: 13px; }.error-message { margin: 12px 20px; color: #ba3434; }.dialog-context { margin: 0 0 12px; color: #71809a; font-size: 13px; }@media (max-width: 620px) { .filters :deep(.el-input), .filters :deep(.el-select) { width: 100%; }.table-footer { align-items: flex-start; flex-direction: column; } }@media (prefers-reduced-motion: reduce) { * { transition: none !important; } }
</style>
