<template>
  <section class="tenants-page" aria-labelledby="tenants-title">
    <header class="page-heading"><div><span class="eyebrow">租户目录</span><h2 id="tenants-title">租户管理</h2><p>创建、筛选并控制平台租户的服务状态。</p></div><el-button type="primary" @click="createDialogVisible = true">创建租户</el-button></header>
    <section class="tenant-panel" aria-label="租户筛选和列表">
      <form class="filters" @submit.prevent="applyFilters"><el-input v-model="filters.keyword" clearable placeholder="按租户代码或名称搜索" aria-label="搜索租户" @clear="applyFilters" /><el-select v-model="filters.status" clearable placeholder="全部状态" aria-label="按状态筛选"><el-option label="正常" :value="1" /><el-option label="已停用" :value="0" /></el-select><el-button native-type="submit">筛选</el-button><el-button text @click="resetFilters">重置</el-button></form>
      <p v-if="error" class="error-message" role="alert">{{ error }}</p>
      <div class="table-wrap" :aria-busy="loading"><table class="tenant-table"><thead><tr><th>租户</th><th>租户代码</th><th>状态</th><th>创建时间</th><th class="actions-col">操作</th></tr></thead><tbody><tr v-for="tenant in tenants" :key="tenant.id"><td class="tenant-name">{{ tenant.name }}</td><td><code>{{ tenant.code }}</code></td><td><el-tag :type="tenant.status === 1 ? 'success' : 'info'" effect="plain">{{ statusLabel(tenant.status) }}</el-tag></td><td>{{ formatTime(tenant.createTime) }}</td><td class="actions-col"><el-button v-if="tenant.status === 1" text type="danger" @click="disableTenant(tenant)">停用</el-button><span v-else class="muted">不可用</span></td></tr><tr v-if="!loading && tenants.length === 0"><td colspan="5" class="empty-state">没有符合条件的租户</td></tr></tbody></table></div>
      <footer class="table-footer"><span>共 {{ total }} 个租户</span><el-pagination v-model:current-page="page" v-model:page-size="pageSize" layout="prev, pager, next" :total="total" :page-sizes="[10, 20, 50]" @current-change="loadTenants" @size-change="changePageSize" /></footer>
    </section>
    <el-dialog v-model="createDialogVisible" title="创建租户" width="460px" :close-on-click-modal="false"><el-form label-position="top" @submit.prevent="createTenant"><el-form-item label="租户名称"><el-input v-model.trim="createForm.name" maxlength="64" placeholder="例如：星海科技" /></el-form-item><el-form-item label="租户代码"><el-input v-model.trim="createForm.code" maxlength="64" placeholder="例如：starsea" /></el-form-item></el-form><template #footer><el-button @click="createDialogVisible = false">取消</el-button><el-button type="primary" :loading="creating" @click="createTenant">创建并生成邀请码</el-button></template></el-dialog>
    <el-dialog v-model="inviteDialogVisible" title="管理员邀请码" width="500px"><p class="invite-help">请将邀请码交给首位租户管理员。邀请码有效期至 {{ inviteExpiresAt || '—' }}。</p><div class="invite-code"><code>{{ inviteCode }}</code><el-button :disabled="!inviteCode" @click="copyInviteCode">复制</el-button></div><template #footer><el-button type="primary" @click="inviteDialogVisible = false">完成</el-button></template></el-dialog>
  </section>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { http } from '../../api/http'
const tenants = ref([]), total = ref(0), page = ref(1), pageSize = ref(20), loading = ref(false), creating = ref(false), error = ref(''), createDialogVisible = ref(false), inviteDialogVisible = ref(false), inviteCode = ref(''), inviteExpiresAt = ref('')
const filters = reactive({ keyword: '', status: undefined })
const createForm = reactive({ code: '', name: '' })
function requestParams() { return { page: page.value, pageSize: pageSize.value, keyword: filters.keyword || undefined, status: filters.status } }
async function loadTenants() { loading.value = true; error.value = ''; try { const response = await http.get('/platform/tenants', { params: requestParams() }); const data = response.data?.data || {}; tenants.value = data.items || []; total.value = data.total || 0; page.value = data.page || page.value; pageSize.value = data.pageSize || pageSize.value } catch (cause) { error.value = cause.response?.data?.msg || '租户列表暂时无法加载' } finally { loading.value = false } }
async function applyFilters() { page.value = 1; await loadTenants() }
async function resetFilters() { filters.keyword = ''; filters.status = undefined; await applyFilters() }
async function changePageSize(size) { pageSize.value = size; page.value = 1; await loadTenants() }
async function createTenant() { if (!createForm.name || !createForm.code) { ElMessage.error('请填写租户名称和代码'); return } creating.value = true; try { const response = await http.post('/platform/tenants', { code: createForm.code, name: createForm.name }); inviteCode.value = response.data?.data?.inviteCode || ''; inviteExpiresAt.value = response.data?.data?.inviteExpiresAt || ''; createDialogVisible.value = false; inviteDialogVisible.value = true; createForm.code = ''; createForm.name = ''; await loadTenants() } catch (cause) { ElMessage.error(cause.response?.data?.msg || '创建租户失败') } finally { creating.value = false } }
async function copyInviteCode() { try { await navigator.clipboard.writeText(inviteCode.value); ElMessage.success('邀请码已复制') } catch { ElMessage.error('复制失败，请手动复制邀请码') } }
async function disableTenant(tenant) { try { await ElMessageBox.confirm(`停用“${tenant.name}”后，该租户将无法登录。`, '确认停用租户', { confirmButtonText: '确认停用', cancelButtonText: '取消', type: 'warning' }) } catch { return } try { await http.post(`/platform/tenants/${tenant.id}/disable`); ElMessage.success('租户已停用'); await loadTenants() } catch (cause) { ElMessage.error(cause.response?.data?.msg || '停用租户失败') } }
function statusLabel(status) { return status === 1 ? '正常' : '已停用' }
function formatTime(value) { return value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '—' }
onMounted(loadTenants)
</script>

<style scoped>
.page-heading { display: flex; justify-content: space-between; align-items: flex-end; gap: 18px; margin-bottom: 25px; }.eyebrow { color: #526aaf; font-size: 12px; font-weight: 700; letter-spacing: .08em; }h2 { margin: 5px 0; color: #182541; font-size: 28px; letter-spacing: -.02em; }.page-heading p { margin: 0; color: #75819a; }.tenant-panel { overflow: hidden; border: 1px solid #e0e5f0; border-radius: 12px; background: #fff; box-shadow: 0 8px 28px rgba(42, 58, 103, .06); }.filters { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; padding: 18px 20px; border-bottom: 1px solid #e8ebf2; background: #fbfcff; }.filters :deep(.el-input) { width: 260px; }.filters :deep(.el-select) { width: 130px; }.table-wrap { overflow-x: auto; }.tenant-table { width: 100%; min-width: 700px; border-collapse: collapse; font-size: 14px; }.tenant-table th { padding: 12px 20px; background: #f6f8fc; color: #6e7991; font-size: 12px; font-weight: 700; letter-spacing: .04em; text-align: left; }.tenant-table td { padding: 15px 20px; border-top: 1px solid #edf0f5; color: #40506f; }.tenant-table tr:hover td { background: #fafbff; }.tenant-name { color: #1d2b49 !important; font-weight: 700; }.tenant-table code, .invite-code code { color: #425a98; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }.actions-col { text-align: right !important; }.empty-state { padding: 38px !important; color: #8791a6 !important; text-align: center; }.muted { color: #98a1b2; }.table-footer { display: flex; justify-content: space-between; align-items: center; gap: 16px; padding: 14px 20px; color: #778298; font-size: 13px; }.error-message { margin: 12px 20px; color: #ba3434; }.invite-help { margin: 0 0 14px; color: #68758d; }.invite-code { display: flex; align-items: center; gap: 10px; padding: 10px 12px; border-radius: 8px; background: #f2f5fd; }.invite-code code { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; }@media (max-width: 620px) { .page-heading { align-items: flex-start; flex-direction: column; }.filters :deep(.el-input), .filters :deep(.el-select) { width: 100%; }.table-footer { align-items: flex-start; flex-direction: column; }.table-footer :deep(.el-pagination) { max-width: 100%; overflow-x: auto; } }@media (prefers-reduced-motion: reduce) { * { transition: none !important; } }
</style>
